### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by khaneliman** [snowfallorg/flake#5]
flake switch on darwin. Any workaround or just not usable when using homebrew module? 

```
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all 
build scripts full access to your system.
```

**Comment by jakehamilton** [comment]
Hmm. I thought that `sudo` was required for `darwin-rebuild`? Does it succeed when not run with `sudo`? If so we can remove the privileged wrapper for Darwin and that should resolve this.
