### ISSUE TITLE
FEATURE REQUEST: "boot" subcommand

### ISSUE THREAD

**Issue by YaroKasear** [snowfallorg/flake#7]
I like to use this command for applying changes and updates for my NixOS/nix-darwin systems, but I'm starting to wonder if immediately switching to new builds is necessarily a good thing. I don't know about nix-darwin, but NixOS has "nixos-rebuild boot" which does everything "switch" does except the actual "switching" part, meaning a reboot would be needed to activate the actual changes (Or running the activation script.) 

This is actually an essential part of the atomic nature of immutable Linux distributions: Nothing changes until a reboot to prevent unpredictable/unstable results.

I don't see Flake offering this as an option, unless the build-system subcommand already does this. I like flake because it spares me from having to use a different command between my NixOS and nix-darwin systems and unifies the experience, more or less.

**Comment by jakehamilton** [comment]
Yeah I think we'll want to add:

- boot
- test
- show
